version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - "./data/db:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    ports:
      - "27017:27017"

  api-server-1:
    image: formio/formio-enterprise:latest
    mem_limit: 1024m
    restart: always
    links:
      - mongo
    volumes:
      - "./certs:/src/certs:ro"
    ports:
      - "3001:3001"
    environment:
      MONGO: mongodb://mongo:27017/cli-test-src
      PORT: 3001
    env_file:
      - .env

  api-server-2:
    image: formio/formio-enterprise:latest
    mem_limit: 1024m
    restart: always
    links:
      - mongo
    volumes:
      - "./certs:/src/certs:ro"
    ports:
      - "3002:3002"
    environment:
      MONGO: mongodb://mongo:27017/cli-test-dst
      PORT: 3002
    env_file:
      - .env