name: Repo

on:
  push:
    branches:
    - '*' # This will make sure all push events on any branch triggers this workflow.

env:
  NODE_VERSION: 20.x
  ADMIN_KEY: testAdminKey
  DOCKER_API_SRC_PORT: 4001
  DOCKER_API_DST_PORT: 4002
  DOCKER_MONGO_SRC: mongodb://mongo:27017/cli-test-src
  DOCKER_MONGO_DST: mongodb://mongo:27017/cli-test-dst
  LICENSE_REMOTE: false
  LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
  API_SRC: http://localhost:4001
  API_DST: http://localhost:4002
  MONGO_SRC: mongodb://localhost:27018/cli-test-src
  MONGO_DST: mongodb://localhost:27018/cli-test-dst

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by ${{ github.event_name }} event."
      - name: Check out repository code ${{ github.repository }} on ${{ github.ref }}
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Installing dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile

      - name: Test
        if: true
        uses: borales/actions-yarn@v4
        with:
          cmd: test
