name: Repo

on:
  push:
    branches:
    - '*' # This will make sure all push events on any branch triggers this workflow.

env:
  NODE_VERSION: 20.x

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by ${{ github.event_name }} event."
      - name: Check out repository code ${{ github.repository }} on ${{ github.ref }}
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Installing dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile

      - name: Test
        if: true
        uses: borales/actions-yarn@v4
        with:
          cmd: test
